spring.application.name=DynamicDataAnalysis

# prefixing every api request
server.servlet.context-path=/api/v1

# Database connection (The one you want to analyze)
spring.datasource.url=jdbc:mysql://localhost:3306/salesdb
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Disable JPA for now (since we aren't saving user info yet)
spring.jpa.hibernate.ddl-auto=none
